package Admin;

/**
 *
 * @author hp
 */
import database.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DaftarKendaraan extends javax.swing.JFrame {

    static void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private final DefaultTableModel model;

    /**
     * Creates new form DaftarKendaraan
     */
    public DaftarKendaraan() {
        initComponents();
        model = new DefaultTableModel ( );
        motor_matic.setModel(model); 
             model.addColumn("motor_matic");
             model.addColumn("harga_sewa_hari");
             getData();
    }
    public void getData( ){
     
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );
 
     try{
           
//membuat statemen untuk memanggil data tb_motor_matic
           koneksi connection = new koneksi();   
           Statement stat = connection.getkoneksi().createStatement( );
           String sql        = "Select * from tb_motor_matic";
           ResultSet res   = stat.executeQuery(sql);
 
           
//pengecekan terhadap data tb_motor_matic
           while(res.next ()){
                Object[] obj = new Object[7];
                obj[0] = res.getString("motor_matic");
                obj[1] = res.getString("harga_sewa_hari");
                model.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        motor_matic = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mobil_matic = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        motor_gigi = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        mobil_manual = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        motor_matic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", ""},
                {null, null},
                {null, null}
            },
            new String [] {
                "Motor Matic", "Harga Sewa/hari"
            }
        ));
        jScrollPane1.setViewportView(motor_matic);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 293, 80));

        mobil_matic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Kijang Innova", "280000"},
                {"Mobilio", "250000"},
                {"Sienta", "250000"}
            },
            new String [] {
                "Mobil Matic", "Harga Sewa/Hari"
            }
        ));
        jScrollPane2.setViewportView(mobil_matic);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 293, 80));

        motor_gigi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Astrea Star", "20000"},
                {"Astrean Grand", "20000"},
                {"Shogun", "20000"}
            },
            new String [] {
                "Motor Gigi", "Harga Sewa/hari"
            }
        ));
        jScrollPane3.setViewportView(motor_gigi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 293, 80));

        mobil_manual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"GR Yaris", "250000"},
                {"Avanza", "250000"},
                {"Xpander", "270000"}
            },
            new String [] {
                "Mobil Manual", "Harga Sewa/hari"
            }
        ));
        jScrollPane4.setViewportView(mobil_manual);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 293, 80));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("UBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 111, 51));

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 114, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Background mobil.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashboardAdmin da = new DashboardAdmin();
        da.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarKendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable mobil_manual;
    private javax.swing.JTable mobil_matic;
    private javax.swing.JTable motor_gigi;
    private javax.swing.JTable motor_matic;
    // End of variables declaration//GEN-END:variables
}
