package User;

/**
 *
 * @author Asus
 */
public class DaftarHargaSewa extends javax.swing.JFrame {

    /**
     * Creates new form menuadmin
     */
    public DaftarHargaSewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        motor_matic = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        motor_gigi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        mobil_matic = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        mobil_manual = new javax.swing.JTable();
        sewa = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        motor_matic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Vario", "50000"},
                {"Nmax", "70000"},
                {"Scoopy", "50000"}
            },
            new String [] {
                "Motor Matic", "Harga Sewa/Hari"
            }
        ));
        jScrollPane2.setViewportView(motor_matic);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 389, 80));

        motor_gigi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Astrea Star", "20000"},
                {"Astrean Grand", "20000"},
                {"Shogun", "20000"}
            },
            new String [] {
                "Motor Gigi", "Harga Sewa/Hari"
            }
        ));
        jScrollPane3.setViewportView(motor_gigi);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 389, 80));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Harga sewa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        mobil_matic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Kijang Innova", "280000"},
                {"Mobilio", "250000"},
                {"Sienta", "250000"}
            },
            new String [] {
                "Mobil Matic", "Harga Sewa/Hari"
            }
        ));
        jScrollPane4.setViewportView(mobil_matic);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 389, 80));

        mobil_manual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"GR Yaris", "250000"},
                {"Avanza", "250000"},
                {"Xpander", "270000"}
            },
            new String [] {
                "Mobil Manual", "Harga Sewa/Hari"
            }
        ));
        jScrollPane5.setViewportView(mobil_manual);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 389, 80));

        sewa.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        sewa.setText("SEWA");
        sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaActionPerformed(evt);
            }
        });
        jPanel1.add(sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        kembali.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Background motor.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaActionPerformed
        // TODO add your handling code here:
        DashboardPenyewaan dp = new DashboardPenyewaan();
        dp.setVisible(true);
        dp.setLocationRelativeTo(null);
        dp.setDefaultCloseOperation(DashboardPenyewaan.EXIT_ON_CLOSE);
    }//GEN-LAST:event_sewaActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
         DashboardUser du = new DashboardUser();
            du.setVisible(true);
            dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarHargaSewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton kembali;
    private javax.swing.JTable mobil_manual;
    private javax.swing.JTable mobil_matic;
    private javax.swing.JTable motor_gigi;
    private javax.swing.JTable motor_matic;
    private javax.swing.JButton sewa;
    // End of variables declaration//GEN-END:variables
}
