package User;
/**
 *
 * @author Asus
 */

import database.koneksi;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Admin.DashboardAdmin;
import User.DashboardUser;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection conn = null;
    PreparedStatement pet = null;
    ResultSet rs = null;
    Object set;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        username3 = new javax.swing.JTextField();
        password3 = new javax.swing.JPasswordField();
        login3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Mouse3 = new javax.swing.JLabel();
        Minimze3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        label_warning = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("WELCOME");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 39));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("JETRIS RENT CAR & MOTORBIKE");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Username");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 158, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Password");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 210, -1, -1));

        username3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel8.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 158, 197, -1));
        jPanel8.add(password3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 197, -1));

        login3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login3.setText("LOGIN USER");
        login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel8.add(login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mouse3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Mouse3.setForeground(new java.awt.Color(255, 255, 255));
        Mouse3.setText("X");
        Mouse3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseMouseClicked(evt);
            }
        });
        jPanel7.add(Mouse3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 0, 24, -1));

        Minimze3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Minimze3.setForeground(new java.awt.Color(255, 255, 255));
        Minimze3.setText("-");
        Minimze3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimzeMouseClicked(evt);
            }
        });
        jPanel7.add(Minimze3, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 0, -1, -1));
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel8.add(label_warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 243, 241, 20));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Belum punya akun?");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 334, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Register");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 334, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("LOGIN ADMIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/Background motor.jpg"))); // NOI18N
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 20, 470, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Register rg = new Register();
        rg.setVisible(true);
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void MinimzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimzeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimzeMouseClicked

    private void MouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MouseMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        conn = koneksi.getkoneksi();
        String Sql = "SELECT * FROM tb_register WHERE username=? and password=?";
        try{
            pet = (PreparedStatement)conn.prepareStatement(Sql);
            pet.setString(1, username3.getText());
            pet.setString(2, password3.getText());
            rs = pet.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "anda berhasil login");
                DashboardUser start = new DashboardUser();
                start.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "username atau password tidak terdaftar","Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:      
        conn = koneksi.getkoneksi();
        String Sql = "SELECT * FROM tb_admin WHERE username=? and password=?";
        try{
            pet = (PreparedStatement)conn.prepareStatement(Sql);
            pet.setString(1, username3.getText());
            pet.setString(2, password3.getText());
            rs = pet.executeQuery();
            if(rs.next()){
                DashboardAdmin start = new DashboardAdmin();
                start.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "username atau password tidak terdaftar","Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Minimze3;
    private javax.swing.JLabel Mouse3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel label_warning;
    private javax.swing.JButton login3;
    private javax.swing.JPasswordField password3;
    private javax.swing.JTextField username3;
    // End of variables declaration//GEN-END:variables
}
